-- AlterTable
ALTER TABLE "employees" ADD COLUMN     "children" JSONB,
ADD COLUMN     "citizenship" TEXT,
ADD COLUMN     "father_name" TEXT,
ADD COLUMN     "gsis_no" TEXT,
ADD COLUMN     "height" TEXT,
ADD COLUMN     "mother_name" TEXT,
ADD COLUMN     "pagibig_no" TEXT,
ADD COLUMN     "permanent_address" TEXT,
ADD COLUMN     "philhealth_no" TEXT,
ADD COLUMN     "place_of_birth" TEXT,
ADD COLUMN     "residential_address" TEXT,
ADD COLUMN     "spouse_business_address" TEXT,
ADD COLUMN     "spouse_contact_no" TEXT,
ADD COLUMN     "spouse_employer" TEXT,
ADD COLUMN     "spouse_name" TEXT,
ADD COLUMN     "spouse_occupation" TEXT,
ADD COLUMN     "sss_no" TEXT,
ADD COLUMN     "tin_no" TEXT,
ADD COLUMN     "weight" TEXT;
